---
title: "Conversations in time: interactive visualization to explore structured temporal data"
author:
- name: Earo Wang
  affiliation: The Univeristy of Auckland
  address:
  - Department of Statistics
  - The Univeristy of Auckland
  - New Zealand
  email: earo.wang@auckland.ac.nz
- name: Dianne Cook
  affiliation: Monash Univerisity
  address:
  - Department of Econometrics and Business Statistics
  - Monash University
  - Australia
  email: dicook@monash.edu
bibliography: references.bib
abstract: >
  An abstract of less than 150 words.
preamble: |
  % Any extra LaTeX you need in the preamble
output: rticles::rjournal_article
---

```{r setup, echo = FALSE, cache = FALSE, include = FALSE}
options("knitr.graphics.auto_pdf" = TRUE)
library(knitr)
opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE, comment = "#>",
  fig.path = 'figure/', fig.align = 'center', fig.show = 'hold',
  cache = TRUE, cache.path = 'cache/',
  out.width = ifelse(is_html_output(), "100%", "\\textwidth")
)
knitr::opts_knit$set(root.dir = here::here())
```

# Introduction

* An ensemble of graphics
* Accelerate the exploratory data visualization process

# Background and motivation

## Interactive visualization systems with linking views

* {ggobi} and {xggobi}
* {cranvas} and {cranvastime}
* [crossfilter.js](http://crossfilter.github.io/crossfilter/) & [dc.js](https://dc-js.github.io/dc.js/)
* {crosstalk} and html widgets

## Tidy temporal data and workflow

The \CRANpkg{tsibble} package extends the `data.frame` and \CRANpkg{tibble} structure to represent temporal data in tidy format [cite]. A tsibble consists of *index*, *key*, and other measured variables in one data frame. The *index* column holds time-based indices. The *key* column(s) uniquely identifies a collection of related observational units during a period of time defined by *index*. They are "sticky" columns to a `tsibble` over the course of transformation.

The \CRANpkg{feasts} and \CRANpkg{fable} packages, part of the **tidyverts** suite, aim to make time series analysis easier. They provide analytical and forecasting tools for the tsibble data structure, generating tsibble-centered workflow. Functions, such as `features()` and `model()`, summarise a sequence of indexed values down to a single statistic or model by every observational unit. The output is a normal table, where each row corresponds to an observational unit denoted by "key". In the context of relational databases, the "key" acts like a foreign key in a reduced form of tsibble, while the index and key together operates like a primary key.

At the early stage of exploratory temporal data analysis, time series plots and scatterplots goes hand by hand. (insert figures below)

# Shared temporal data for coordinated views

The \pkg{tsibbletalk} package, inspired by the \CRANpkg{crosstalk} package, introduces a shared tsibble data structure to enable reactivity for temporal data (i.e. a `tsibble`). The `as_shared_tsibble()` function turns a tsibble to a mutable tsibble `SharedTsibbleData`, as an R6 subclass of `SharedData` from {crosstalk}. A *tsibble* data object holds a set of interrelated series, identified by the "key", in a data frame. When the "key" includes more than two variables, there can exist intrinsic structures in all combinations of variables: either nesting or crossing. (Add an example here)

The `spec` argument in the `as_shared_tsibble()` function takes a symbolic formula to allow users to specify structural combinations, using `/` and `*` adopted from Wilkinson notation (10.2307/2346786) for nesting and crossing respectively.

* Nesting variables generate hierarchical tree, hence `plotly_key_tree()`. Overview and navigation made easier.
* One-to-many linking: marking a single point of interest highlights all other points that share particular data values (categorical linking)
* Lists of key values, and json
* Self-linking: a single data source

# Slicing and dicing time

The other critical aspect of a tsibble is "index", that provides foundational temporal context. A common tool in time series analytical toolkit is seasonal plots that lay time series not on the whole time scale, but on an origin-less relative time unit, for example `gg_season()` in the {feasts} package. It helps to examine and emphasise periodic/aperiodic patterns, comparing to time series plots that primarily focus on trends. Standard seasonal plots break the overall time into two components: seasonal periods on the x-axis, and grouped by their corresponding lower-resolution time. For example, monthly data can be decomposed into months separated by years, and hourly data into hours grouped by days. Data collected at lower-level resolutions often exhibits more than one seasonal patterns. To discover typical seasonal or non-typical profiles, it is helpful to quickly browse through many possible periods. Interactivity ought to be enabled.

The {tsibbletalk} package provides a pair of UI and server functions, as a shiny module, to help with finding interesting time slices in a shiny application. The pair, decoupled to `tsibbleDiceUI()` and `tsibbleDiceServer()`, presents a clean interface and forms a resusable piece. Like all shiny modules, users should supply a unique session id. The UI function `tsibbleDiceUI()` shows a slider that controls the number of periods, and a plot specified by users. The server function `tsibbleDiceServer()` is the workhorse, transforming data and updating the plot. It expects a `ggplot` (converted to `plotly` via `ggplotly()`) or `plotly` object. This plot can be line charts, or other graphical elements (such as boxplots). But it assumes that tsibble's time index is plotted on the x-axis. The other mandatory argument is to specify the number of seasonal periods that requires shifting.

(Data flows) Transformed data generally requires redrawing the plot, and worsen the performance of shiny. The underlying tsibble data is called back and transformed in R. Using the `plotly.js` react method, only transformed data is sent to the server side, while keeping the rest configuration unchanged (e.g. layout and graphical elements). It is performant, and users will not experience notable delay in response to the change in the slider input. Dissect time index, and propagate transformed data to shiny server.

# Case study: monthly domestic tourist trips in Australia

# Conclusions and discussions

# References {-}
